account_id = "03e7294bdb3750ed5a0d6afef6d770e4"
compatibility_date = "2022-01-24"
name = "webhook-dev"
route = ""
type = "webpack"
vars = {ENVIRONMENT = "development"}
webpack_config = "webpack.config.js"
workers_dev = true
zone_id = "73599f8e5f0cdb85f65ae7b132f574fc"
[env.production]
name = "webhook"
vars = {ENVIRONMENT = "production"}
